version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro

    itinterview-app:
        image: itinterview
        external_links:
            - itinterview-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/itinterview
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - VIRTUAL_HOST=itinterview.co.kr
        ports:
            - 8080:8080
    itinterview-postgresql:
        extends:
            file: postgresql.yml
            service: itinterview-postgresql
